#!/bin/bash

whitespace=""
for FILE in `git diff-index --name-only HEAD --` ; do
  if test -e $FILE; then
    if [[ -n `grep "\\s\\s*$" $FILE` ]]; then whitespace="$whitespace $FILE"; fi
    # Remove trailing whitespace
    sed -i "s/\\s\\s*$//g" $FILE
    # Remove tabs
    sed -i "s/\t/  /g" $FILE
    # If a file is ruby, check for syntax errors
    if [[ -n `find $FILE -regex ".*\.rb$"` ]]; then
      if [[ "$fail" -eq 0 || -z "$fail" ]]; then
        `ruby -c $FILE 1> /dev/null`; fail=$?
      else
        `ruby -c $FILE 1> /dev/null`
      fi
    fi
  fi
done

# Built-in git checks
git diff-index --check HEAD --

if [[ "$fail" -ne 0 && -n "$fail" ]]; then
  echo "Syntax Errors Found. Aborting commit"
  exit 1
fi

for FILE in $whitespace; do
  echo "Whitespace problem fixed. Please re-add '$FILE' to your commit"
done
if [[ -n "$whitespace" ]]; then exit 1; fi

# Check that project metadata files exist
for FILE in "LICENSE" "README.rdoc" "VERSION" "Gemfile" "Gemfile.lock" ".gitignore"; do
  if test ! -e $FILE; then
    echo "$FILE not present. Aborting commit"
    exit 1
  fi
done
