  @runner = VirtualMonkey::MysqlChefRunner.new(ENV['DEPLOYMENT'])
  @runner.behavior(:stop_all)
  @runner.set_var(:set_variation_lineage)
  @runner.set_var(:set_variation_container)
  @runner.set_var(:set_variation_storage_type)

#  @runner.set_var(:setup_dns, "virtualmonkey_shared_resources") # DNSMadeEasy
  @runner.behavior(:launch_all)

#  @runner.behavior(:wait_for_all, "booting")
  @runner.behavior(:wait_for_all, "operational")
  @runner.behavior(:setup_block_device)
#  @runner.behavior(:do_backup)
#  @runner.behavior(:do_force_reset)
#  @runner.behavior(:do_restore)
  @runner.behavior(:test_multicloud)
  @runner.behavior(:check_monitoring)
#  @runner.behavior(:check_mysql_monitoring)
  @runner.behavior(:run_reboot_operations)
  @runner.behavior(:check_monitoring)
#  @runner.behavior(:run_restore_with_timestamp_override)
#  @runner.behavior(:run_logger_audit)
  @runner.behavior(:stop_all, true)
#  @runner.behavior(:release_dns)
