  @runner = VirtualMonkey::SimpleRunner.new(ENV['DEPLOYMENT'])
  @runner.behavior(:stop_all)
  @runner.behavior(:launch_all)
  @runner.behavior(:wait_for_all, "operational")
  @runner.behavior(:reboot_all)
  @runner.behavior(:wait_for_all, "operational")
  @runner.behavior(:reboot_all)
  @runner.behavior(:wait_for_all, "operational")
  @runner.behavior(:reboot_all)
  @runner.behavior(:wait_for_all, "operational")
  @runner.behavior(:reboot_all)
  @runner.behavior(:wait_for_all, "operational")
  @runner.behavior(:reboot_all)
  @runner.behavior(:wait_for_all, "operational")
  @runner.behavior(:reboot_all)
  @runner.behavior(:wait_for_all, "operational")
